# Generated by Django 4.2.5 on 2023-09-11 11:59

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', models.BigIntegerField()),
                ('image', models.ImageField(upload_to=client.models.getFileName)),
            ],
        ),
    ]
