# Generated by Django 4.2.5 on 2023-09-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='phone_number',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
